{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "40c70909-52f4-4383-9833-f62c5c0110e1",
   "metadata": {},
   "outputs": [],
   "source": [
    "# app.py\n",
    "\n",
    "import pandas as pd\n",
    "import streamlit as st\n",
    "import plotly.express as px\n",
    "from pathlib import Path\n",
    "from statsmodels.tsa.holtwinters import ExponentialSmoothing\n",
    "\n",
    "# 1. Upload des fichiers\n",
    "st.sidebar.title(\"Chargement des fichiers\")\n",
    "\n",
    "uploaded_data = st.sidebar.file_uploader(\n",
    "    \"Fichiers Réels (TPS, TPSM, MM MOIS 4, WEAR PART)\", \n",
    "    type=[\"xlsx\"], accept_multiple_files=True\n",
    ")\n",
    "\n",
    "if not uploaded_data:\n",
    "    st.sidebar.error(\"⚠️ Charge au moins un fichier de données réelles.\")\n",
    "    st.stop()\n",
    "\n",
    "@st.cache_data(ttl=3600)\n",
    "def load_real_data(files):\n",
    "    dfs = []\n",
    "    for f in files:\n",
    "        df = pd.read_excel(f, sheet_name=\"Sheet1\", engine=\"openpyxl\")\n",
    "        dfs.append(df)\n",
    "    df_all = pd.concat(dfs, ignore_index=True)\n",
    "    df_all[\"Posting Date\"] = pd.to_datetime(df_all[\"Posting Date\"])\n",
    "    df_all[\"Year\"]  = df_all[\"Posting Date\"].dt.year\n",
    "    df_all[\"Month\"] = df_all[\"Posting Date\"].dt.month\n",
    "    df_all[\"Cost\"]  = df_all[\"In profit center local currency\"].fillna(0)\n",
    "    return df_all\n",
    "\n",
    "df = load_real_data(uploaded_data)\n",
    "\n",
    "# 2. Calcul Budget et Forecast automatiques\n",
    "@st.cache_data(ttl=3600)\n",
    "def compute_budget_forecast(df):\n",
    "    # 2.1 Agrégation mensuelle globale\n",
    "    series = (\n",
    "        df\n",
    "        .groupby([df[\"Posting Date\"].dt.to_period(\"M\")])[\"Cost\"]\n",
    "        .sum()\n",
    "        .sort_index()\n",
    "        .to_timestamp()\n",
    "    )\n",
    "\n",
    "    # 2.2 Budget par croissance moyenne des 12 derniers mois\n",
    "    # Taux moyen de croissance mensuel sur 12 mois glissants\n",
    "    pct_change_12 = series.pct_change(periods=12).dropna()\n",
    "    avg_growth = pct_change_12.mean()\n",
    "    # Budget = dernier réel * (1 + avg_growth)\n",
    "    last_real = series.iloc[-1]\n",
    "    budget = pd.Series(\n",
    "        [last_real * (1 + avg_growth)],\n",
    "        index=[series.index[-1] + pd.offsets.MonthBegin()]\n",
    "    )\n",
    "\n",
    "    # 2.3 Forecast par lissage exponentiel simple (Holt-Winters sans saison)\n",
    "    model = ExponentialSmoothing(series, trend=\"add\", seasonal=None, initialization_method=\"estimated\")\n",
    "    fit = model.fit()\n",
    "    # On prédit au même horizon que le budget (1 mois en avant)\n",
    "    forecast = fit.forecast(1)\n",
    "\n",
    "    # 2.4 DataFrame final\n",
    "    dfB = pd.DataFrame({\n",
    "        \"Period\": series.index.tolist() + budget.index.tolist(),\n",
    "        \"Budget\": pd.concat([pd.Series(series.values, index=series.index), budget]).values\n",
    "    })\n",
    "    dfF = pd.DataFrame({\n",
    "        \"Period\": series.index.tolist() + forecast.index.tolist(),\n",
    "        \"Forecast\": pd.concat([series, forecast]).values\n",
    "    })\n",
    "    # Séparer Year / Month\n",
    "    for dfX in (dfB, dfF):\n",
    "        dfX[\"Year\"]  = dfX[\"Period\"].dt.year\n",
    "        dfX[\"Month\"] = dfX[\"Period\"].dt.month\n",
    "    return dfB, dfF\n",
    "\n",
    "dfB, dfF = compute_budget_forecast(df)\n",
    "\n",
    "# 3. Sidebar – Filtres\n",
    "st.sidebar.title(\"Filtres\")\n",
    "years  = sorted(df[\"Year\"].unique())\n",
    "year   = st.sidebar.selectbox(\"Année\", years, index=len(years)-1)\n",
    "plants = [\"Toutes\"] + sorted(df[\"Plant\"].dropna().unique().tolist())\n",
    "plant  = st.sidebar.selectbox(\"Usine\", plants)\n",
    "\n",
    "mask = (df[\"Year\"] == year)\n",
    "if plant != \"Toutes\":\n",
    "    mask &= (df[\"Plant\"] == plant)\n",
    "df_filt = df[mask]\n",
    "\n",
    "# 4. Onglets\n",
    "tabs = st.tabs([\n",
    "    \"Overview\", \"Total & Benchmark\", \"Cost w/o PM\",\n",
    "    \"By Location\", \"By Equipment\", \"By Vendor\",\n",
    "    \"By Material\", \"By Order\", \"By Stoppages\"\n",
    "])\n",
    "\n",
    "# 4.1 Overview\n",
    "with tabs[0]:\n",
    "    st.header(\"Overview – Actual vs Budget vs Forecast\")\n",
    "    real = (\n",
    "        df_filt\n",
    "        .groupby([df_filt[\"Posting Date\"].dt.to_period(\"M\")])[\"Cost\"]\n",
    "        .sum()\n",
    "        .to_timestamp()\n",
    "        .reset_index()\n",
    "        .rename(columns={\"Posting Date\":\"Period\", \"Cost\":\"Actual\"})\n",
    "    )\n",
    "    comp = (\n",
    "        real\n",
    "        .merge(dfB, on=[\"Period\"], how=\"left\")\n",
    "        .merge(dfF, on=[\"Period\"], how=\"left\")\n",
    "    )\n",
    "    fig = px.line(\n",
    "        comp,\n",
    "        x=\"Period\",\n",
    "        y=[\"Actual\",\"Budget\",\"Forecast\"],\n",
    "        labels={\"value\":\"Coût\", \"Period\":\"Mois\"},\n",
    "        markers=True\n",
    "    )\n",
    "    st.plotly_chart(fig, use_container_width=True)\n",
    "\n",
    "# 4.2 Total & Benchmark\n",
    "with tabs[1]:\n",
    "    st.header(\"Total Cost & Benchmark\")\n",
    "    agg = df_filt.groupby(\"Plant\")[\"Cost\"].sum().reset_index().sort_values(\"Cost\", ascending=False)\n",
    "    st.plotly_chart(px.bar(agg, x=\"Plant\", y=\"Cost\", labels={\"Cost\":\"Coût total\"}), use_container_width=True)\n",
    "\n",
    "# 4.3 Cost without PM order\n",
    "with tabs[2]:\n",
    "    st.header(\"Cost without PM order\")\n",
    "    wo_pm = df_filt[df_filt[\"Order\"].isna()]\n",
    "    agg = wo_pm.groupby(df_filt[\"Posting Date\"].dt.to_period(\"M\"))[\"Cost\"].sum().to_timestamp().reset_index()\n",
    "    agg.columns = [\"Period\",\"Cost\"]\n",
    "    st.plotly_chart(px.bar(agg, x=\"Period\", y=\"Cost\", labels={\"Cost\":\"Coût sans PM\"}), use_container_width=True)\n",
    "\n",
    "# 4.4 Cost at Functional Location\n",
    "with tabs[3]:\n",
    "    st.header(\"Cost at Functional Location\")\n",
    "    agg = df_filt.groupby(\"Functional Area\")[\"Cost\"].sum().reset_index().sort_values(\"Cost\", ascending=False)\n",
    "    st.plotly_chart(px.bar(agg, x=\"Functional Area\", y=\"Cost\"), use_container_width=True)\n",
    "\n",
    "# 4.5 Cost at Equipment\n",
    "with tabs[4]:\n",
    "    st.header(\"Cost at Equipment\")\n",
    "    agg = df_filt.groupby(\"Equipment\")[\"Cost\"].sum().reset_index().sort_values(\"Cost\", ascending=False)\n",
    "    st.plotly_chart(px.bar(agg, x=\"Equipment\", y=\"Cost\"), use_container_width=True)\n",
    "\n",
    "# 4.6 Cost at Vendor\n",
    "with tabs[5]:\n",
    "    st.header(\"Cost at Vendor\")\n",
    "    agg = df_filt.groupby(\"Vendor\")[\"Cost\"].sum().reset_index().sort_values(\"Cost\", ascending=False)\n",
    "    st.plotly_chart(px.bar(agg, x=\"Vendor\", y=\"Cost\"), use_container_width=True)\n",
    "\n",
    "# 4.7 Cost at Material\n",
    "with tabs[6]:\n",
    "    st.header(\"Cost at Material\")\n",
    "    agg = df_filt.groupby(\"Material\")[\"Cost\"].sum().reset_index().sort_values(\"Cost\", ascending=False)\n",
    "    st.plotly_chart(px.bar(agg, x=\"Material\", y=\"Cost\"), use_container_width=True)\n",
    "\n",
    "# 4.8 Cost at Order\n",
    "with tabs[7]:\n",
    "    st.header(\"Cost at Order\")\n",
    "    agg = df_filt.groupby(\"Order\")[\"Cost\"].sum().reset_index().sort_values(\"Cost\", ascending=False)\n",
    "    st.plotly_chart(px.bar(agg, x=\"Order\", y=\"Cost\"), use_container_width=True)\n",
    "\n",
    "# 4.9 Cost at Stoppages\n",
    "with tabs[8]:\n",
    "    st.header(\"Cost at Stoppages\")\n",
    "    agg = (\n",
    "        df_filt\n",
    "        .groupby([\"Stop ID\",\"Stop Cause\"])[\"Cost\"]\n",
    "        .sum()\n",
    "        .reset_index()\n",
    "        .sort_values(\"Cost\", ascending=False)\n",
    "    )\n",
    "    st.plotly_chart(\n",
    "        px.bar(agg, x=\"Stop ID\", y=\"Cost\", hover_data=[\"Stop Cause\"]),\n",
    "        use_container_width=True\n",
    "    )\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
